INSERT INTO Books (title, author, publication_year, genre, is_available) VALUES
('To Kill a Mockingbird', 'Harper Lee', 1960, 'Fiction', TRUE),
('A Brief History of Time', 'Stephen Hawking', 1988, 'Science', TRUE),
('1984', 'George Orwell', 1949, 'Fiction', TRUE),
('The Art of Computer Programming', 'Donald E. Knuth', 1968, 'Fiction', TRUE),
('The Diary of a Young Girl', 'Anne Frank', 1947, 'Fiction', TRUE),
('Green Eggs and Ham', 'Dr. Seuss', 1960, 'Children', TRUE),
('The Hobbit', 'J.R.R. Tolkien', 1937, 'Fiction', TRUE),
('The Da Vinci Code', 'Dan Brown', 2003, 'Fiction', TRUE),
('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 2011, 'Fiction', TRUE),
('The Story of Art', 'E. H. Gombrich', 1950, 'Art', TRUE),
('Cosmos', 'Carl Sagan', 1980, 'Science', TRUE),
('The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', 1979, 'Fantasy', TRUE),
('Dune', 'Frank Herbert', 1965, 'Science', TRUE),
('Educated', 'Tara Westover', 2018, 'Biography', TRUE),
('The Great Gatsby', 'F. Scott Fitzgerald', 1925, 'Fiction', TRUE),
('Pride and Prejudice', 'Jane Austen', 1813, 'Fiction', TRUE),
('The Lord of the Rings', 'J.R.R. Tolkien', 1954, 'Fantasy', TRUE),
('The Martian', 'Andy Weir', 2011, 'Science', TRUE),
('Becoming', 'Michelle Obama', 2018, 'Biography', TRUE),
('Atomic Habits', 'James Clear', 2018, 'Non-Fiction', TRUE),
('The Silent Patient', 'Alex Michaelides', 2019, 'Mystery', TRUE),
('Where the Crawdads Sing', 'Delia Owens', 2018, 'Fiction', TRUE),
('The Very Hungry Caterpillar', 'Eric Carle', 1969, 'Children', TRUE),
('Steve Jobs', 'Walter Isaacson', 2011, 'Biography', TRUE),
('Clean Code', 'Robert C. Martin', 2008, 'Technology', TRUE),
('Thinking, Fast and Slow', 'Daniel Kahneman', 2011, 'Science', TRUE),
('The Alchemist', 'Paulo Coelho', 1988, 'Fiction', TRUE),
('A People''s History of the United States', 'Howard Zinn', 1980, 'History', TRUE),
('The Girl with the Dragon Tattoo', 'Stieg Larsson', 2005, 'Mystery', TRUE),
('Leonardo daVinci', 'Walter Isaacson', 2017, 'Biography', TRUE);